export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const SWITCH_SOURCE = 'SWITCH_SOURCE';
export const SOURCE_API = 'API';
export const SOURCE_LOCAL = 'LOCAL';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';